#!/bin/bash -e

chown -R mysql:mysql /var/lib/mysql
mysql_install_db --user mysql > /dev/null

chown -R mysql:adm /var/log/mysql

rootpw=${MYSQL_ROOT_PASSWORD:-""}
mydb=${MYSQL_DATABASE:-""}
myuser=${MYSQL_USER:-""}
mypass=${MYSQL_PASSWORD:-""}
mychset=${MYSQL_CHARACTER_SET:-"utf8"}
mycollate=${MYSQL_COLLATE:-"utf8_bin"}
myhost=${GRANT_HOSTNAME:-"%"}

tfile=`mktemp`
if [ ! -f "$tfile" ]; then
        return 1
fi

# The FLUSH PRIVILEGES here is to disable --skip-grant-tables.
cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
UPDATE user SET password=PASSWORD("$rootpw") WHERE user='root';
UPDATE user SET Grant_priv='Y', Super_priv='Y' WHERE User='root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'$myhost' IDENTIFIED BY '$rootpw';
EOF

if [[ $mydb != "" ]]; then
    echo "CREATE DATABASE IF NOT EXISTS \`$mydb\` CHARACTER SET \`$mychset\` COLLATE \`$mycollate\`;" >> $tfile

    if [[ $myuser != "" ]]; then
        echo "GRANT ALL ON \`$mydb\`.* TO '$myuser'@'$myhost' IDENTIFIED BY '$mypass';" >> $tfile
    fi
fi

/usr/sbin/mysqld --bootstrap --user=mysql <$tfile
rm -f $tfile

exec supervisord
